services:
  php:
    build: .
    container_name: app-php
    ports:
      - "8000:80"
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpredis
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: app-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql

  redis:
    image: redis:7-alpine
    container_name: app-redis
    ports:
      - "6379:6379"

volumes:
  dbdata: